CREATE DATABASE tt;
USE tt;
CREATE TABLE province(
pid INT PRIMARY KEY AUTO_INCREMENT,
pname VARCHAR(20) UNIQUE
);
CREATE TABLE city(
cid INT PRIMARY KEY AUTO_INCREMENT,
cname VARCHAR(20) UNIQUE,
pid INT,
CONSTRAINT fk_p_c FOREIGN KEY (pid) REFERENCES province(pid) ON DELETE SET NULL ON UPDATE CASCADE  
);
INSERT INTO province VALUES(NULL,'山东');
INSERT INTO city VALUES(NULL,'济南',1);

ALTER TABLE city DROP FOREIGN KEY fk_p_c;
ALTER TABLE city DROP INDEX fk_p_c;

ALTER TABLE city ADD CONSTRAINT fk_p_c FOREIGN KEY(pid) REFERENCES province(pid) ON UPDATE CASCADE ON DELETE SET NULL

ALTER TABLE city DROP FOREIGN KEY fk_p_c;

DROP INDEX fk_p_c ON city;

DELETE FROM province;
TRUNCATE TABLE province;
TRUNCATE TABLE city;
DROP TABLE province;
DROP DATABASE tt;
 
